name: Run doc tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**/docs/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      data-transforms-changed: ${{ steps.filter.outputs.data-transforms-changed }}
      another-path-changed: ${{ steps.filter.outputs.another-path-changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            data-transforms-changed:
              - 'data-transforms/**'

  run-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Run tests for data-transforms if changed
        if: needs.setup.outputs.data-transforms-changed == 'true'
        run: echo "Running tests for data-transforms" && cd data-transforms/flatten && node test.js
