name: Run doc tests

on: pull_request

jobs:
  find-and-run-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: get-changed-files
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm i

      - name: Run test.js if present
        run: |
          #!/bin/bash
          cd data-transforms/flatten && node test.js
